### PR TITLE
SAK-509 dependency inversion

### PR DESCRIPTION
**Pull request by rafalkanski**
@filipgolonka @wsromek @arkadiuszmalina @bartosz-kahl 

**DONE**

Since now package requires only two virtual packages and `PHP 5.5>=`, focusing on interfaces.

### CODE REVIEW

**Comment by filipgolonka** [comment]
:+1:

**Comment by wsromek** [comment]
👍

**Comment by rafalkanski** [comment]
a jakas nagroda ? order czy cos ? :D

**Comment by arkadiuszmalina** [comment]
👍

**Comment by barkahl** [comment]
👍

**Pull request merged**
